# Generated by Django 5.2.8 on 2025-12-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo_livro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título do livro'),
        ),
    ]
